//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orc.FeatureToggles.Example.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orc.FeatureToggles.Example.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Toggles Test.
        /// </summary>
        internal static string Orc_FeatureToggles_Example_MainViewModel_Title {
            get {
                return ResourceManager.GetString("Orc_FeatureToggles_Example_MainViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature toggles.
        /// </summary>
        internal static string Orc_FeatureToggles_Example_RibbonView_FeatureToggles {
            get {
                return ResourceManager.GetString("Orc_FeatureToggles_Example_RibbonView_FeatureToggles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string Orc_FeatureToggles_Example_RibbonView_Manage {
            get {
                return ResourceManager.GetString("Orc_FeatureToggles_Example_RibbonView_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super cool feature NOT enabled.
        /// </summary>
        internal static string Orc_FeatureToggles_Example_StatusBarViewModel_SuperCoolFeatureDisabled {
            get {
                return ResourceManager.GetString("Orc_FeatureToggles_Example_StatusBarViewModel_SuperCoolFeatureDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super cool feature ENABLED.
        /// </summary>
        internal static string Orc_FeatureToggles_Example_StatusBarViewModel_SuperCoolFeatureEnabled {
            get {
                return ResourceManager.GetString("Orc_FeatureToggles_Example_StatusBarViewModel_SuperCoolFeatureEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When this feature toggle is enabled, it will show SUPER COOL FEATURE in the status bar.
        /// </summary>
        internal static string Orc_FeatureToggles_Example_SuperCoolFeatureToggle_Description {
            get {
                return ResourceManager.GetString("Orc_FeatureToggles_Example_SuperCoolFeatureToggle_Description", resourceCulture);
            }
        }
    }
}
